window.OLIVIA_TEMPLATE_DATA = {
  modules: [
    {
      id: "dashboard",
      num: "一",
      title: "首页仪表盘",
      icon: "🏠",
      intro: "今日概览、数据看板、快捷入口、时间线",
      tabs: ["今日概览", "数据看板", "快捷入口", "时间线"],
      prompt: "请帮我汇总今日工作学习情况：任务完成率、学习时长、番茄钟数量、AI对话次数、目标进度，并给出今日建议。",
      tabGroups: [
        { name: "总览", tabs: ["今日概览", "数据看板"] },
        { name: "工具", tabs: ["快捷入口", "时间线"] }
      ],
      items: [
        {
          title: "今日待办任务",
          summary: "今天还有 5 个待办任务，其中 2 个高优先级",
          status: "进行中",
          category: "今日概览",
          audience: "自己",
          tags: ["待办", "今日"],
          date: "今天",
          heat: 90,
          ai: false,
          icon: "📋",
          color: "blue"
        },
        {
          title: "本周学习时长趋势",
          summary: "本周累计学习 12.5 小时，比上周增长 15%",
          status: "可复用",
          category: "数据看板",
          audience: "自己",
          tags: ["学习", "统计"],
          date: "本周",
          heat: 75,
          ai: false,
          icon: "📊",
          color: "green"
        }
      ]
    },
    {
      id: "project",
      num: "二",
      title: "项目管理中心",
      icon: "📋",
      intro: "任务计划、看板视图、日历规划、AI日报",
      tabs: ["合集管理", "任务看板", "日历规划", "日报生成", "项目模板"],
      prompt: "请帮我拆解项目任务、识别风险、生成待确认事项，并输出一版适合汇报的项目进展说明。",
      tabGroups: [
        { name: "执行", tabs: ["合集管理", "任务看板", "日历规划"] },
        { name: "沉淀", tabs: ["日报生成", "项目模板"] }
      ],
      items: [
        {
          title: "充电桩运营平台需求推进",
          summary: "跟进业务方需求确认、数据口径、后台管理权限与上线节奏。",
          status: "进行中",
          category: "合集管理",
          audience: "业务/研发",
          tags: ["充电桩", "需求"],
          date: "2026-07-16",
          heat: 95,
          ai: true,
          icon: "🔋",
          color: "green"
        },
        {
          title: "项目风险池",
          summary: "记录供应商、接口、数据质量、跨部门协作等风险与处理进度。",
          status: "持续维护",
          category: "合集管理",
          audience: "项目组",
          tags: ["风险", "协作"],
          date: "长期",
          heat: 82,
          ai: false,
          icon: "🧯",
          color: "orange"
        }
      ]
    },
    {
      id: "ai-center",
      num: "二",
      title: "AI全能助手",
      icon: "🤖",
      intro: "零配置多模型智能助手：通用对话、行业资料联网调研、公文汇报材料生成、自媒体文案撰写、图片解析、英语辅助。支持豆包/DeepSeek/Kimi/通义千问一键切换，开箱即用。",
      tabs: ["通用对话", "行业调研", "公文材料", "自媒体文案", "图片解析", "英语辅助"],
      prompt: "你是AI全能助手，支持通用对话问答、行业资料联网调研（AI产品、新能源项目管理、PM方法论）、公文/汇报材料生成、自媒体文案撰写（小红书/公众号/抖音）、图片解析（饮食热量识别、截图需求拆解）、英语辅助（翻译、作文批改、托业答题解析）。请根据用户需求选择合适的能力。",
      tabGroups: [
        { name: "核心能力", tabs: ["通用对话", "行业调研", "公文材料"] },
        { name: "创作&工具", tabs: ["自媒体文案", "图片解析", "英语辅助"] }
      ],
      items: [
        {
          title: "项目周报生成",
          summary: "输入任务、风险、会议纪要后，自动生成适合汇报的周报草稿。",
          status: "可用",
          category: "公文材料",
          audience: "项目经理",
          tags: ["周报", "公文"],
          date: "已沉淀",
          heat: 93,
          ai: true,
          icon: "📮",
          color: "blue"
        },
        {
          title: "AI产品竞品拆解",
          summary: "从定位、用户、能力、交互、商业化、可借鉴点拆解 AI 产品。",
          status: "优化中",
          category: "行业调研",
          audience: "AI产品经理",
          tags: ["竞品", "AI产品"],
          date: "本周",
          heat: 89,
          ai: true,
          icon: "🔎",
          color: "purple"
        },
        {
          title: "小红书文案生成",
          summary: "输入产品/场景/卖点，自动生成小红书风格文案、标题、标签和封面文案。",
          status: "可用",
          category: "自媒体文案",
          audience: "创作者",
          tags: ["小红书", "文案"],
          date: "已沉淀",
          heat: 91,
          ai: true,
          icon: "📝",
          color: "pink"
        },
        {
          title: "新能源行业资讯搜集",
          summary: "联网搜集新能源项目管理、政策动态、技术趋势等最新资讯，结构化输出。",
          status: "可用",
          category: "行业调研",
          audience: "项目经理",
          tags: ["新能源", "资讯"],
          date: "实时",
          heat: 88,
          ai: true,
          icon: "⚡",
          color: "green"
        }
      ]
    },
    {
      id: "learning",
      num: "四",
      title: "学习成长中心",
      icon: "📝",
      intro: "学习任务、专注计时(番茄钟)、知识笔记(PARA四区+AI归类/标签/摘要/整理+全文搜索+Markdown预览)、目标管理(OKR+AI智能拆解+进度看板+目标对齐)",
      tabs: ["学习任务", "专注计时", "知识笔记", "目标管理", "成就系统"],
      prompt: "请帮我规划学习任务、安排复习计划、整理知识笔记（PARA体系：Projects有明确目标的项目/Areas持续维护的领域/Resources感兴趣的资源/Archives已归档的内容），并给出学习建议。",
      tabGroups: [
        { name: "学习", tabs: ["学习任务", "专注计时"] },
        { name: "知识", tabs: ["知识笔记", "目标管理"] },
        { name: "激励", tabs: ["成就系统"] }
      ],
      items: [
        {
          title: "AI产品经理能力地图",
          summary: "补充模型能力、RAG、Agent、MCP、AI办公产品等学习主题。",
          status: "进行中",
          category: "目标管理",
          audience: "AI产品经理",
          tags: ["AI产品", "能力地图"],
          date: "本月",
          heat: 78,
          ai: true,
          icon: "🧠",
          color: "purple"
        },
        {
          title: "番茄工作法",
          summary: "25分钟专注+5分钟休息，高效学习工作法。",
          status: "核心原则",
          category: "专注计时",
          audience: "自己",
          tags: ["番茄钟", "专注"],
          date: "长期",
          heat: 88,
          ai: false,
          icon: "🍅",
          color: "orange"
        }
      ]
    },
    {
      id: "english",
      num: "五",
      title: "英语学习",
      icon: "🎯",
      intro: "背单词(艾宾浩斯·九大场景词库·170+词)、影子跟读(AI评分·55句)、听力训练(8大场景·50句)、学习计划、错题本、语法练习(9大主题)、口语测评(4大模式)",
      tabs: ["背单词", "影子跟读", "听力训练", "亲子英语", "商务英语", "托业考试", "日常英语", "旅行英语", "科技英语", "学术英语", "四级词汇", "六级词汇", "学习计划", "错题本", "语法练习", "口语测评"],
      prompt: "请作为英语学习助手，帮助我背单词、练习跟读、训练听力、制定学习计划、攻克语法难点。根据我的水平给出适合的学习内容。",
      tabGroups: [
        { name: "技能训练", tabs: ["背单词", "影子跟读", "听力训练"] },
        { name: "场景词库", tabs: ["亲子英语", "商务英语", "托业考试", "日常英语", "旅行英语"] },
        { name: "考试&学术", tabs: ["四级词汇", "六级词汇", "科技英语", "学术英语"] },
        { name: "系统提升", tabs: ["学习计划", "错题本", "语法练习", "口语测评"] }
      ],
      items: [
        {
          title: "艾宾浩斯复习曲线",
          summary: "根据遗忘曲线自动安排单词复习节奏：1天/2天/4天/7天/15天。",
          status: "核心原则",
          category: "背单词",
          audience: "自己",
          tags: ["记忆", "复习"],
          date: "长期",
          heat: 92,
          ai: false,
          icon: "📈",
          color: "blue"
        },
        {
          title: "影子跟读训练法",
          summary: "逐句播放原音→跟读录音→AI语音评分，三维度反馈：准确度、流利度、节奏。",
          status: "核心原则",
          category: "影子跟读",
          audience: "自己",
          tags: ["口语", "发音"],
          date: "长期",
          heat: 90,
          ai: true,
          icon: "🎙️",
          color: "pink"
        },
        /* ─── 亲子英语场景词库 ─── */
        {
          title: "日常对话常用句型",
          summary: "起床/吃饭/穿衣/出门/睡觉等生活场景的核心英语句型，配有中文对照和语音提示。",
          status: "可复用",
          category: "亲子英语",
          audience: "家长",
          tags: ["日常", "对话", "场景"],
          date: "长期",
          heat: 88,
          ai: false,
          icon: "🗣️",
          color: "blue"
        },
        {
          title: "绘本英语推荐",
          summary: "精选 20 本适合 3-8 岁的英语绘本清单，包含 Brown Bear、Goodnight Moon 等经典书目。",
          status: "推荐",
          category: "亲子英语",
          audience: "家长",
          tags: ["绘本", "阅读", "启蒙"],
          date: "长期",
          heat: 82,
          ai: false,
          icon: "📚",
          color: "green"
        },
        {
          title: "亲子游戏英语用语",
          summary: "捉迷藏、拼图、画画等亲子游戏中的英语互动用语，寓教于乐。",
          status: "可复用",
          category: "亲子英语",
          audience: "家长",
          tags: ["游戏", "互动", "趣味"],
          date: "长期",
          heat: 78,
          ai: false,
          icon: "🎮",
          color: "orange"
        },
        {
          title: "儿童英语启蒙方法",
          summary: "TPR 全身反应法、自然拼读、儿歌输入等科学启蒙方法论，适合零基础家长。",
          status: "参考",
          category: "亲子英语",
          audience: "家长",
          tags: ["启蒙", "方法", "教育"],
          date: "长期",
          heat: 85,
          ai: false,
          icon: "💡",
          color: "purple"
        },
        {
          title: "亲子共学打卡记录",
          summary: "每日亲子英语学习打卡模板，记录学习内容、时长和孩子反应，形成学习习惯。",
          status: "进行中",
          category: "亲子英语",
          audience: "自己",
          tags: ["打卡", "习惯", "记录"],
          date: "今天",
          heat: 72,
          ai: false,
          icon: "✅",
          color: "teal"
        },
        /* ─── 商务英语场景词库 ─── */
        {
          title: "会议发言常用句型",
          summary: "开场白、表达观点、赞同/反对、总结发言等会议场景高频句型及实战示例。",
          status: "可复用",
          category: "商务英语",
          audience: "职场人",
          tags: ["会议", "发言", "表达"],
          date: "长期",
          heat: 90,
          ai: false,
          icon: "🎤",
          color: "blue"
        },
        {
          title: "邮件写作模板",
          summary: "请求帮助、进度汇报、会议邀请、感谢回复等高频商务邮件模板，可直接套用。",
          status: "可复用",
          category: "商务英语",
          audience: "职场人",
          tags: ["邮件", "写作", "模板"],
          date: "长期",
          heat: 88,
          ai: false,
          icon: "✉️",
          color: "green"
        },
        {
          title: "谈判用语",
          summary: "报价、还价、条件协商、达成共识等商务谈判核心用语和策略表达。",
          status: "参考",
          category: "商务英语",
          audience: "职场人",
          tags: ["谈判", "沟通", "策略"],
          date: "长期",
          heat: 80,
          ai: false,
          icon: "🤝",
          color: "orange"
        },
        {
          title: "汇报表达",
          summary: "周报/月报/季度汇报中的数据描述、趋势分析、问题反馈等常用表达句式。",
          status: "可复用",
          category: "商务英语",
          audience: "职场人",
          tags: ["汇报", "数据", "分析"],
          date: "长期",
          heat: 85,
          ai: false,
          icon: "📊",
          color: "purple"
        },
        {
          title: "商务电话用语",
          summary: "电话预约、自我介绍、转接留言、电话会议等场景的常用英语话术。",
          status: "可复用",
          category: "商务英语",
          audience: "职场人",
          tags: ["电话", "沟通", "话术"],
          date: "长期",
          heat: 76,
          ai: false,
          icon: "📞",
          color: "teal"
        },
        {
          title: "跨文化沟通注意事项",
          summary: "不同文化背景下的商务礼仪、禁忌话题、非语言沟通差异等实用指南。",
          status: "参考",
          category: "商务英语",
          audience: "职场人",
          tags: ["跨文化", "礼仪", "沟通"],
          date: "长期",
          heat: 74,
          ai: true,
          icon: "🌍",
          color: "pink"
        },
        /* ─── 托业考试场景词库 ─── */
        {
          title: "听力 Part 1 高频词汇",
          summary: "照片描述题核心词汇：位置关系、人物动作、场景描述等高频出题词分类整理。",
          status: "可复用",
          category: "托业考试",
          audience: "考生",
          tags: ["听力", "Part1", "词汇"],
          date: "长期",
          heat: 92,
          ai: false,
          icon: "🎧",
          color: "blue"
        },
        {
          title: "听力 Part 2 常见场景",
          summary: "问答题高频场景：办公室事务、旅行安排、餐厅购物、电话留言等场景问答集锦。",
          status: "可复用",
          category: "托业考试",
          audience: "考生",
          tags: ["听力", "Part2", "场景"],
          date: "长期",
          heat: 88,
          ai: false,
          icon: "🎧",
          color: "green"
        },
        {
          title: "阅读高频语法点",
          summary: "托业阅读常考语法：时态一致、被动语态、从句嵌套、虚拟语气等考点梳理。",
          status: "参考",
          category: "托业考试",
          audience: "考生",
          tags: ["阅读", "语法", "考点"],
          date: "长期",
          heat: 86,
          ai: false,
          icon: "📖",
          color: "orange"
        },
        {
          title: "商务词汇速记",
          summary: "托业必背 500 核心商务词汇，按金融、人事、营销、IT 等主题分类速记。",
          status: "核心原则",
          category: "托业考试",
          audience: "考生",
          tags: ["词汇", "商务", "速记"],
          date: "长期",
          heat: 95,
          ai: false,
          icon: "📝",
          color: "purple"
        },
        {
          title: "模拟题练习计划",
          summary: "8 周托业备考模拟题训练计划，每周安排 2 套完整模拟 + 薄弱环节专项突破。",
          status: "进行中",
          category: "托业考试",
          audience: "自己",
          tags: ["模拟题", "计划", "备考"],
          date: "本周",
          heat: 80,
          ai: false,
          icon: "📅",
          color: "teal"
        },
        {
          title: "考试时间管理技巧",
          summary: "托业考试 120 分钟时间分配策略：听力 45 分钟、阅读 75 分钟的 pacing 方法论。",
          status: "参考",
          category: "托业考试",
          audience: "考生",
          tags: ["时间", "技巧", "策略"],
          date: "长期",
          heat: 78,
          ai: false,
          icon: "⏱️",
          color: "pink"
        },
        /* ─── 科技英语场景词库 ─── */
        {
          title: "IT互联网核心术语",
          summary: "涵盖算法、云计算、网络安全、数据库、机器学习等20个核心技术词汇，附代码示例和应用场景。",
          status: "可复用",
          category: "科技英语",
          audience: "技术人员",
          tags: ["科技", "IT", "术语"],
          date: "长期",
          heat: 90,
          ai: false,
          icon: "💻",
          color: "teal"
        },
        {
          title: "技术文档阅读技巧",
          summary: "英文技术文档阅读方法论：扫读定位、精读理解、术语积累、代码对照阅读策略。",
          status: "参考",
          category: "科技英语",
          audience: "技术人员",
          tags: ["文档", "阅读", "方法"],
          date: "长期",
          heat: 82,
          ai: true,
          icon: "📖",
          color: "blue"
        },
        /* ─── 学术英语场景词库 ─── */
        {
          title: "学术论文写作词汇",
          summary: "涵盖摘要、引用、假设、方法论、回归分析等20个学术写作核心词汇，适合论文写作参考。",
          status: "可复用",
          category: "学术英语",
          audience: "学生/研究者",
          tags: ["学术", "论文", "写作"],
          date: "长期",
          heat: 85,
          ai: false,
          icon: "🎓",
          color: "purple"
        },
        {
          title: "学术写作句型模板",
          summary: "引言、文献综述、方法描述、结果讨论、结论等论文各部分常用学术英语句型模板。",
          status: "可复用",
          category: "学术英语",
          audience: "学生/研究者",
          tags: ["句型", "模板", "论文"],
          date: "长期",
          heat: 80,
          ai: true,
          icon: "✍️",
          color: "blue"
        },
        /* ─── 四级词汇 ─── */
        {
          title: "CET-4 高频核心词汇",
          summary: "精选20个大学英语四级考试高频核心词汇，涵盖大纲重点词汇，附真题例句和考点解析。",
          status: "核心原则",
          category: "四级词汇",
          audience: "考生",
          tags: ["四级", "CET4", "高频"],
          date: "长期",
          heat: 95,
          ai: false,
          icon: "📚",
          color: "blue"
        },
        {
          title: "四级备考攻略",
          summary: "听力、阅读、翻译、写作四大题型备考策略，附时间规划和模拟题训练计划。",
          status: "参考",
          category: "四级词汇",
          audience: "考生",
          tags: ["四级", "备考", "策略"],
          date: "本月",
          heat: 88,
          ai: true,
          icon: "📝",
          color: "orange"
        },
        /* ─── 六级词汇 ─── */
        {
          title: "CET-6 高频核心词汇",
          summary: "精选20个大学英语六级考试高频核心词汇，涵盖六级难点词汇，附真题例句和考点解析。",
          status: "核心原则",
          category: "六级词汇",
          audience: "考生",
          tags: ["六级", "CET6", "高频"],
          date: "长期",
          heat: 92,
          ai: false,
          icon: "📖",
          color: "pink"
        },
        {
          title: "六级翻译高分技巧",
          summary: "汉译英翻译技巧：长句拆分、主被动转换、文化负载词处理、句式多样性等高分策略。",
          status: "参考",
          category: "六级词汇",
          audience: "考生",
          tags: ["六级", "翻译", "技巧"],
          date: "本月",
          heat: 85,
          ai: true,
          icon: "✏️",
          color: "purple"
        }
      ]
    },
    {
      id: "reading",
      num: "六",
      title: "读书管理",
      icon: "📖",
      intro: "书架管理(在读/想读/已读+筛选排序)、阅读进度追踪、阅读计时器、读书笔记(4类)、书评系统、书籍详情视图、笔记导出Markdown、阅读统计(月度/标签/速度/评分/热力图/时长)、年度目标+连续打卡、AI推荐书单(30本)",
      tabs: ["书架", "阅读进度", "读书笔记", "阅读统计"],
      prompt: "请帮我管理读书计划：推荐书籍、整理笔记、追踪进度、生成阅读统计。",
      tabGroups: [
        { name: "管理", tabs: ["书架", "阅读进度"] },
        { name: "沉淀", tabs: ["读书笔记", "阅读统计"] }
      ],
      items: [
        {
          title: "AI产品经理实战手册",
          summary: "从需求定义到上线运营的完整方法论，涵盖AI产品全生命周期管理。",
          status: "在读",
          category: "书架",
          audience: "AI产品经理",
          tags: ["AI", "产品", "方法论"],
          date: "2026-07-01",
          heat: 85,
          ai: false,
          icon: "📘",
          color: "purple"
        },
        {
          title: "深度工作",
          summary: "Cal Newport 著，关于专注力管理的经典，教你如何在分心时代保持高效。",
          status: "想读",
          category: "书架",
          audience: "自己",
          tags: ["效率", "专注", "经典"],
          date: "待读",
          heat: 70,
          ai: false,
          icon: "📗",
          color: "green"
        },
        {
          title: "思考，快与慢",
          summary: "Daniel Kahneman 著，诺贝尔经济学奖得主的决策心理学巨著。",
          status: "想读",
          category: "书架",
          audience: "自己",
          tags: ["心理学", "决策", "经典"],
          date: "待读",
          heat: 78,
          ai: false,
          icon: "📕",
          color: "pink"
        },
        {
          title: "原则",
          summary: "Ray Dalio 著，桥水基金创始人的生活和工作原则集。",
          status: "想读",
          category: "书架",
          audience: "自己",
          tags: ["管理", "决策", "成长"],
          date: "待读",
          heat: 75,
          ai: false,
          icon: "📙",
          color: "orange"
        },
        {
          title: "精益创业",
          summary: "Eric Ries 著，现代创业方法论圣经，MVP理念的经典来源。",
          status: "已读",
          category: "书架",
          audience: "产品经理",
          tags: ["创业", "方法论", "MVP"],
          date: "2026-06-15",
          heat: 82,
          ai: false,
          icon: "📓",
          color: "blue"
        },
        {
          title: "非暴力沟通",
          summary: "Marshall Rosenberg 著，以共情为基础的高效沟通方法。",
          status: "想读",
          category: "书架",
          audience: "自己",
          tags: ["沟通", "心理学", "成长"],
          date: "待读",
          heat: 72,
          ai: false,
          icon: "📔",
          color: "teal"
        },
        {
          title: "AI 3.0",
          summary: "Melanie Mitchell 著，深入浅出讲解人工智能的现状与局限。",
          status: "在读",
          category: "书架",
          audience: "AI产品经理",
          tags: ["AI", "技术", "认知"],
          date: "2026-07-20",
          heat: 80,
          ai: false,
          icon: "📘",
          color: "blue"
        },
        {
          title: "纳瓦尔宝典",
          summary: "纳瓦尔·拉维坎特的财富与幸福人生智慧合集。",
          status: "已读",
          category: "书架",
          audience: "自己",
          tags: ["成长", "投资", "人生"],
          date: "2026-05-10",
          heat: 76,
          ai: false,
          icon: "📗",
          color: "green"
        },
        {
          title: "被讨厌的勇气",
          summary: "岸见一郎著，阿德勒心理学入门，教你如何获得真正的自由。",
          status: "想读",
          category: "书架",
          audience: "自己",
          tags: ["心理学", "阿德勒", "成长"],
          date: "待读",
          heat: 78,
          ai: false,
          icon: "📕",
          color: "pink"
        },
        {
          title: "原子习惯",
          summary: "James Clear 著，教你如何通过微小改变建立好习惯、打破坏习惯。",
          status: "想读",
          category: "书架",
          audience: "自己",
          tags: ["习惯", "自律", "成长"],
          date: "待读",
          heat: 85,
          ai: false,
          icon: "📘",
          color: "blue"
        },
        {
          title: "人类简史",
          summary: "尤瓦尔·赫拉利著，从认知革命到科学革命的人类发展史诗。",
          status: "想读",
          category: "书架",
          audience: "自己",
          tags: ["历史", "人类学", "思维"],
          date: "待读",
          heat: 88,
          ai: false,
          icon: "📙",
          color: "orange"
        },
        {
          title: "影响力",
          summary: "Robert Cialdini 著，说服心理学的经典之作，揭示6大影响力武器。",
          status: "想读",
          category: "书架",
          audience: "职场人",
          tags: ["心理学", "沟通", "影响力"],
          date: "待读",
          heat: 80,
          ai: false,
          icon: "📗",
          color: "green"
        },
        {
          title: "Hooked（上瘾）",
          summary: "Nir Eyal 著，揭示产品设计中的上瘾模型：触发→行动→奖励→投入。",
          status: "已读",
          category: "书架",
          audience: "产品经理",
          tags: ["产品", "设计", "心理学"],
          date: "2026-06-01",
          heat: 84,
          ai: false,
          icon: "📓",
          color: "purple"
        },
        {
          title: "创新者的窘境",
          summary: "Clayton Christensen 著，为什么优秀企业会失败？颠覆式创新理论经典。",
          status: "想读",
          category: "书架",
          audience: "产品经理",
          tags: ["创新", "商业", "管理"],
          date: "待读",
          heat: 82,
          ai: false,
          icon: "📕",
          color: "pink"
        },
        {
          title: "心流",
          summary: "米哈里·契克森米哈赖著，最优体验心理学，如何在生活中找到心流。",
          status: "想读",
          category: "书架",
          audience: "自己",
          tags: ["心理学", "专注", "幸福"],
          date: "待读",
          heat: 77,
          ai: false,
          icon: "📔",
          color: "teal"
        },
        {
          title: "代码整洁之道",
          summary: "Robert Martin著，讲解如何编写整洁、可读、可维护的高质量代码。",
          status: "已读",
          category: "书架",
          audience: "开发团队",
          tags: ["编程", "代码质量", "最佳实践"],
          date: "2026-03-10",
          heat: 88,
          ai: false,
          icon: "📗",
          color: "green"
        },
        {
          title: "设计模式",
          summary: "GoF著，经典软件设计模式指南，面向对象设计的基石之作。",
          status: "想读",
          category: "书架",
          audience: "开发团队",
          tags: ["设计模式", "架构", "面向对象"],
          date: "待读",
          heat: 85,
          ai: false,
          icon: "📘",
          color: "blue"
        },
        {
          title: "重构：改善既有代码的设计",
          summary: "Martin Fowler著，系统讲解代码重构的原则与手法，提升代码质量。",
          status: "在读",
          category: "书架",
          audience: "开发团队",
          tags: ["重构", "代码优化", "软件工程"],
          date: "2026-07-20",
          heat: 82,
          ai: false,
          icon: "📙",
          color: "orange"
        },
        {
          title: "高效能人士的七个习惯",
          summary: "Stephen Covey著，经典自我管理方法论，从依赖到互赖的成长路径。",
          status: "已读",
          category: "书架",
          audience: "团队",
          tags: ["自我管理", "习惯", "领导力"],
          date: "2026-01-18",
          heat: 90,
          ai: false,
          icon: "📕",
          color: "pink"
        },
        {
          title: "格鲁夫给经理人的第一课",
          summary: "Andy Grove著，英特尔前CEO分享高产出管理理念与实务经验。",
          status: "想读",
          category: "书架",
          audience: "管理者",
          tags: ["管理", "领导力", "产出"],
          date: "待读",
          heat: 78,
          ai: false,
          icon: "📘",
          color: "purple"
        },
        {
          title: "OKR工作法",
          summary: "Christina Wodtke著，讲解OKR目标管理方法的落地实践与技巧。",
          status: "想读",
          category: "书架",
          audience: "管理者",
          tags: ["OKR", "目标管理", "团队协作"],
          date: "待读",
          heat: 76,
          ai: false,
          icon: "📗",
          color: "teal"
        },
        {
          title: "百年孤独",
          summary: "加西亚·马尔克斯著，魔幻现实主义文学巨著，布恩迪亚家族七代传奇。",
          status: "想读",
          category: "书架",
          audience: "自己",
          tags: ["文学", "魔幻现实主义", "经典"],
          date: "待读",
          heat: 80,
          ai: false,
          icon: "📔",
          color: "purple"
        },
        {
          title: "活出生命的意义",
          summary: "Viktor Frankl著，集中营幸存者探寻人生意义的深刻反思与启示。",
          status: "已读",
          category: "书架",
          audience: "自己",
          tags: ["哲学", "人生意义", "心理学"],
          date: "2026-05-22",
          heat: 92,
          ai: false,
          icon: "📕",
          color: "pink"
        },
        {
          title: "学会提问",
          summary: "Neil Browne著，批判性思维入门经典，培养独立思考与分析能力。",
          status: "想读",
          category: "书架",
          audience: "自己",
          tags: ["批判性思维", "逻辑", "思考"],
          date: "待读",
          heat: 74,
          ai: false,
          icon: "📘",
          color: "blue"
        },
        {
          title: "金字塔原理",
          summary: "Barbara Minto著，麦肯锡思维方法论，构建清晰有逻辑的表达框架。",
          status: "在读",
          category: "书架",
          audience: "团队",
          tags: ["逻辑思维", "表达", "写作"],
          date: "2026-07-15",
          heat: 83,
          ai: false,
          icon: "📙",
          color: "orange"
        },
        {
          title: "系统之美",
          summary: "Donella Meadows著，系统思维入门指南，理解复杂系统的运作规律。",
          status: "想读",
          category: "书架",
          audience: "自己",
          tags: ["系统思维", "复杂性", "决策"],
          date: "待读",
          heat: 77,
          ai: false,
          icon: "📗",
          color: "teal"
        },
        {
          title: "乔布斯传",
          summary: "Walter Isaacson著，苹果创始人授权传记，记录创新与执着的人生。",
          status: "已读",
          category: "书架",
          audience: "自己",
          tags: ["传记", "创新", "创业"],
          date: "2026-04-08",
          heat: 88,
          ai: false,
          icon: "📔",
          color: "purple"
        },
        {
          title: "经济学原理",
          summary: "N. Gregory Mankiw著，经济学入门经典教材，构建经济学核心思维框架。",
          status: "想读",
          category: "书架",
          audience: "自己",
          tags: ["经济学", "基础理论", "市场"],
          date: "待读",
          heat: 72,
          ai: false,
          icon: "📘",
          color: "green"
        },
        {
          title: "穷查理宝典",
          summary: "Charlie Munger著，芒格智慧箴言录，跨学科思维模型与投资哲学。",
          status: "已读",
          category: "书架",
          audience: "自己",
          tags: ["投资", "思维模型", "哲学"],
          date: "2026-06-15",
          heat: 91,
          ai: false,
          icon: "📕",
          color: "blue"
        }
      ]
    },
    {
      id: "pm-knowledge",
      num: "七",
      title: "AI产品经理知识库",
      icon: "🧠",
      intro: "行业动态(8)、方法论(8)、案例库(8)、学习路径(6)、工具资源(8)、AI术语表(8)、AI快速生成(PRD/竞品分析/用户故事/需求评审/路线图)，覆盖AI产品全生命周期",
      tabs: ["行业动态", "方法论", "案例库", "学习路径", "工具资源", "AI术语表", "AI快速生成"],
      prompt: "请用 AI 产品经理视角分析这个产品或功能：目标用户、核心场景、关键能力、交互亮点、商业价值、风险限制、我可以迁移的启发。",
      tabGroups: [
        { name: "认知", tabs: ["行业动态", "方法论"] },
        { name: "实践", tabs: ["案例库", "学习路径"] },
        { name: "资源", tabs: ["工具资源", "AI术语表"] },
        { name: "AI工具", tabs: ["AI快速生成"] }
      ],
      items: [
        /* ─── 行业动态 ─── */
        {
          title: "AI办公助手产品观察",
          summary: "观察文档、表格、会议、邮件场景里的 AI 辅助方式和入口设计。Notion AI、Copilot、飞书智能伙伴等产品对比。",
          status: "持续观察",
          category: "行业动态",
          audience: "AI产品经理",
          tags: ["AI办公", "产品观察", "竞品"],
          date: "长期",
          heat: 91,
          ai: true,
          icon: "💼",
          color: "purple"
        },
        {
          title: "Agent工作流能力地图",
          summary: "梳理工具调用、记忆、计划、执行、授权、回滚等关键能力。覆盖单Agent与多Agent协作模式。",
          status: "进行中",
          category: "行业动态",
          audience: "AI产品经理",
          tags: ["Agent", "Workflow", "能力地图"],
          date: "本月",
          heat: 96,
          ai: true,
          icon: "🕸️",
          color: "blue"
        },
        {
          title: "RAG技术产品化趋势",
          summary: "检索增强生成(RAG)在企业知识库、客服、文档问答场景的产品化落地。向量检索、rerank、chunk策略。",
          status: "持续观察",
          category: "行业动态",
          audience: "AI产品经理",
          tags: ["RAG", "知识库", "检索"],
          date: "本月",
          heat: 88,
          ai: true,
          icon: "📚",
          color: "green"
        },
        {
          title: "多模态AI产品演进",
          summary: "GPT-4o、Gemini等多模态模型催生的产品形态：AI绘图、视频生成、语音助手、实时翻译等。",
          status: "持续观察",
          category: "行业动态",
          audience: "AI产品经理",
          tags: ["多模态", "GPT-4o", "趋势"],
          date: "本月",
          heat: 93,
          ai: true,
          icon: "🎨",
          color: "pink"
        },
        {
          title: "AI编程助手赛道分析",
          summary: "GitHub Copilot、Cursor、Codeium、通义灵码等AI编程工具的产品差异化和商业模式对比。",
          status: "已分析",
          category: "行业动态",
          audience: "AI产品经理",
          tags: ["AI编程", "Cursor", "竞品"],
          date: "本周",
          heat: 90,
          ai: true,
          icon: "💻",
          color: "blue"
        },
        {
          title: "MCP协议生态观察",
          summary: "Anthropic推出的MCP(Model Context Protocol)如何标准化AI与外部工具的连接，生态参与者分析。",
          status: "持续观察",
          category: "行业动态",
          audience: "AI产品经理",
          tags: ["MCP", "协议", "生态"],
          date: "本月",
          heat: 87,
          ai: true,
          icon: "🔌",
          color: "purple"
        },
        {
          title: "AI Agent商业化模式",
          summary: "从SaaS到Agent-as-a-Service：按任务计费、按结果计费、Agent市场等新型商业化探索。",
          status: "研究",
          category: "行业动态",
          audience: "AI产品经理",
          tags: ["商业化", "Agent", "模式"],
          date: "本月",
          heat: 85,
          ai: true,
          icon: "💰",
          color: "orange"
        },
        {
          title: "国内外大模型能力对比",
          summary: "GPT/Claude/Gemini vs 通义/文心/智谱/豆包/Kimi：能力差异、价格、适用场景和选型建议。",
          status: "定期更新",
          category: "行业动态",
          audience: "AI产品经理",
          tags: ["大模型", "对比", "选型"],
          date: "本月",
          heat: 92,
          ai: true,
          icon: "📊",
          color: "teal"
        },
        /* ─── 方法论 ─── */
        {
          title: "AI产品需求文档模板",
          summary: "专为AI产品设计的PRD模板：模型能力需求、Prompt设计、评测标准、边界条件、降级策略、数据飞轮。",
          status: "可复用",
          category: "方法论",
          audience: "AI产品经理",
          tags: ["PRD", "模板", "需求"],
          date: "已沉淀",
          heat: 95,
          ai: false,
          icon: "📝",
          color: "blue"
        },
        {
          title: "AI产品评测体系搭建",
          summary: "从自动评测到人工评测：构建AI产品质量评估体系。包括准确率、召回率、人工评分、A/B测试。",
          status: "可复用",
          category: "方法论",
          audience: "AI产品经理",
          tags: ["评测", "质量", "指标"],
          date: "已沉淀",
          heat: 89,
          ai: true,
          icon: "📏",
          color: "purple"
        },
        {
          title: "Prompt工程方法论",
          summary: "System Prompt、Few-shot、Chain-of-Thought、ReAct等Prompt设计模式与最佳实践。",
          status: "可复用",
          category: "方法论",
          audience: "AI产品经理",
          tags: ["Prompt", "工程", "最佳实践"],
          date: "已沉淀",
          heat: 93,
          ai: true,
          icon: "🎯",
          color: "green"
        },
        {
          title: "AI功能灰度发布策略",
          summary: "AI功能的灰度发布方法论：从小流量验证到全量发布。包含效果监控、回滚机制、用户反馈收集。",
          status: "可复用",
          category: "方法论",
          audience: "AI产品经理",
          tags: ["灰度", "发布", "监控"],
          date: "已沉淀",
          heat: 82,
          ai: false,
          icon: "🚦",
          color: "orange"
        },
        {
          title: "AI产品数据飞轮设计",
          summary: "如何设计用户反馈闭环，让使用数据持续优化模型效果。隐式反馈与显式反馈的采集设计。",
          status: "可复用",
          category: "方法论",
          audience: "AI产品经理",
          tags: ["数据飞轮", "反馈", "优化"],
          date: "已沉淀",
          heat: 86,
          ai: true,
          icon: "🔄",
          color: "pink"
        },
        {
          title: "AI产品合规与安全",
          summary: "内容安全、数据隐私、算法备案、生成内容标识。AI产品合规checklist和风险应对策略。",
          status: "参考",
          category: "方法论",
          audience: "AI产品经理",
          tags: ["合规", "安全", "隐私"],
          date: "已沉淀",
          heat: 80,
          ai: false,
          icon: "🛡️",
          color: "teal"
        },
        {
          title: "AI产品用户体验设计",
          summary: "AI交互设计原则：可解释性、可控性、容错性、渐进式披露。从命令式到对话式到主动式交互。",
          status: "可复用",
          category: "方法论",
          audience: "AI产品经理",
          tags: ["UX", "交互", "设计"],
          date: "已沉淀",
          heat: 88,
          ai: false,
          icon: "✨",
          color: "purple"
        },
        {
          title: "AI产品成本优化策略",
          summary: "Token成本优化、模型路由策略、缓存机制、蒸馏与量化。在效果和成本间找到平衡点。",
          status: "参考",
          category: "方法论",
          audience: "AI产品经理",
          tags: ["成本", "优化", "ROI"],
          date: "已沉淀",
          heat: 84,
          ai: true,
          icon: "💡",
          color: "blue"
        },
        /* ─── 案例库 ─── */
        {
          title: "案例：飞书智能伙伴产品设计",
          summary: "飞书如何将AI能力融入文档、表格、会议场景。从入口设计到能力边界的完整拆解。",
          status: "已拆解",
          category: "案例库",
          audience: "AI产品经理",
          tags: ["飞书", "AI办公", "拆解"],
          date: "2026-07",
          heat: 90,
          ai: true,
          icon: "📝",
          color: "blue"
        },
        {
          title: "案例：Cursor AI编程体验设计",
          summary: "Cursor如何通过Tab补全、Chat、Composer三个层级设计AI编程体验。交互创新与用户留存。",
          status: "已拆解",
          category: "案例库",
          audience: "AI产品经理",
          tags: ["Cursor", "AI编程", "交互"],
          date: "2026-07",
          heat: 92,
          ai: true,
          icon: "💻",
          color: "purple"
        },
        {
          title: "案例：Perplexity AI搜索",
          summary: "Perplexity如何重新定义搜索：追问、引用、Pro Search。AI原生搜索产品的差异化设计。",
          status: "已拆解",
          category: "案例库",
          audience: "AI产品经理",
          tags: ["Perplexity", "搜索", "AI原生"],
          date: "2026-06",
          heat: 88,
          ai: true,
          icon: "🔍",
          color: "teal"
        },
        {
          title: "案例：Notion AI文档助手",
          summary: "Notion AI如何在不破坏写作流的前提下嵌入AI。Inline AI、Q&A、 autofill等功能拆解。",
          status: "已拆解",
          category: "案例库",
          audience: "AI产品经理",
          tags: ["Notion", "文档", "嵌入"],
          date: "2026-06",
          heat: 85,
          ai: true,
          icon: "📄",
          color: "green"
        },
        {
          title: "案例：ChatGPT产品演进",
          summary: "从GPT-3.5到GPT-4o，ChatGPT的产品迭代路径。GPTs商店、Memory、Canvas等关键功能分析。",
          status: "已拆解",
          category: "案例库",
          audience: "AI产品经理",
          tags: ["ChatGPT", "迭代", "产品演进"],
          date: "2026-07",
          heat: 95,
          ai: true,
          icon: "🤖",
          color: "orange"
        },
        {
          title: "案例：Kimi长文本处理",
          summary: "月之暗面Kimi如何以200万字长文本处理作为核心差异化。长文本场景的产品设计和用户洞察。",
          status: "已拆解",
          category: "案例库",
          audience: "AI产品经理",
          tags: ["Kimi", "长文本", "差异化"],
          date: "2026-05",
          heat: 87,
          ai: true,
          icon: "📖",
          color: "pink"
        },
        {
          title: "案例：Midjourney AI绘图",
          summary: "Midjourney如何通过Discord社区+Prompt驱动打造AI绘图产品标杆。商业模式与社区运营。",
          status: "已拆解",
          category: "案例库",
          audience: "AI产品经理",
          tags: ["Midjourney", "绘图", "社区"],
          date: "2026-05",
          heat: 84,
          ai: true,
          icon: "🎨",
          color: "purple"
        },
        {
          title: "案例：通义千问产品矩阵",
          summary: "阿里通义千问的产品矩阵策略：从C端APP到B端API，从通用模型到垂直行业模型的布局。",
          status: "已拆解",
          category: "案例库",
          audience: "AI产品经理",
          tags: ["通义", "产品矩阵", "战略"],
          date: "2026-06",
          heat: 83,
          ai: true,
          icon: "🌐",
          color: "blue"
        },
        /* ─── 学习路径 ─── */
        {
          title: "AI产品经理能力地图",
          summary: "从传统PM到AI PM的转型路径：技术认知、产品设计、数据分析、模型评测四大能力域。",
          status: "进行中",
          category: "学习路径",
          audience: "AI产品经理",
          tags: ["能力地图", "转型", "路径"],
          date: "本月",
          heat: 96,
          ai: true,
          icon: "🗺️",
          color: "purple"
        },
        {
          title: "大模型技术基础入门",
          summary: "PM需要掌握的AI技术基础：Transformer、注意力机制、预训练与微调、上下文窗口、Token等核心概念。",
          status: "学习中",
          category: "学习路径",
          audience: "AI产品经理",
          tags: ["技术", "大模型", "基础"],
          date: "本月",
          heat: 90,
          ai: false,
          icon: "🧠",
          color: "blue"
        },
        {
          title: "AI产品经理必读书单",
          summary: "从《AI 3.0》到《Prompt工程指南》：AI产品经理必读的12本书+10篇论文+5门课程。",
          status: "持续更新",
          category: "学习路径",
          audience: "AI产品经理",
          tags: ["书单", "学习", "资源"],
          date: "本月",
          heat: 85,
          ai: false,
          icon: "📚",
          color: "green"
        },
        {
          title: "AI产品实战项目清单",
          summary: "通过实战项目提升AI产品能力：从Prompt优化→RAG应用→Agent设计→多模态产品的阶梯式项目。",
          status: "规划中",
          category: "学习路径",
          audience: "AI产品经理",
          tags: ["实战", "项目", "练习"],
          date: "本月",
          heat: 88,
          ai: true,
          icon: "🛠️",
          color: "orange"
        },
        {
          title: "AI产品经理面试准备",
          summary: "AI产品经理面试高频题：模型选型、效果评测、产品设计、案例分析。含答题框架和参考答案。",
          status: "准备中",
          category: "学习路径",
          audience: "AI产品经理",
          tags: ["面试", "求职", "准备"],
          date: "本月",
          heat: 82,
          ai: false,
          icon: "🎯",
          color: "pink"
        },
        {
          title: "AI产品社区与信息源",
          summary: "优质AI产品信息源：HuggingFace、AI Product Hunt、机器之心、量子位等。构建个人信息获取体系。",
          status: "持续维护",
          category: "学习路径",
          audience: "AI产品经理",
          tags: ["信息源", "社区", "RSS"],
          date: "长期",
          heat: 78,
          ai: false,
          icon: "📡",
          color: "teal"
        },
        /* ─── 工具资源 ─── */
        {
          title: "原型设计工具盘点",
          summary: "Figma、Sketch、Axure、即时设计等原型工具在AI产品中的应用对比，含AI插件生态评估。",
          status: "持续维护",
          category: "工具资源",
          audience: "AI产品经理",
          tags: ["原型", "设计", "工具"],
          date: "长期",
          heat: 85,
          ai: false,
          icon: "🎨",
          color: "purple"
        },
        {
          title: "AI产品分析工具箱",
          summary: "PostHog、Mixpanel、Amplitude等数据分析工具在AI产品中的使用，含A/B测试和用户行为追踪。",
          status: "可复用",
          category: "工具资源",
          audience: "AI产品经理",
          tags: ["分析", "数据", "工具"],
          date: "长期",
          heat: 82,
          ai: true,
          icon: "📊",
          color: "blue"
        },
        {
          title: "Prompt管理与测试工具",
          summary: "LangSmith、Promptflow、Dify等Prompt管理工具对比，含版本控制、A/B测试和评估指标。",
          status: "可复用",
          category: "工具资源",
          audience: "AI产品经理",
          tags: ["Prompt", "测试", "工具"],
          date: "长期",
          heat: 88,
          ai: true,
          icon: "🔧",
          color: "orange"
        },
        {
          title: "AI模型评估平台",
          summary: "OpenAI Evals、HELM、BIG-bench等模型评估平台使用指南，含自定义评估指标设计。",
          status: "参考",
          category: "工具资源",
          audience: "AI产品经理",
          tags: ["评估", "模型", "工具"],
          date: "长期",
          heat: 80,
          ai: false,
          icon: "📋",
          color: "green"
        },
        {
          title: "向量数据库选型指南",
          summary: "Pinecone、Weaviate、Milvus、Qdrant等向量数据库对比，含性能基准和成本分析。",
          status: "参考",
          category: "工具资源",
          audience: "AI产品经理",
          tags: ["向量数据库", "RAG", "选型"],
          date: "长期",
          heat: 84,
          ai: false,
          icon: "🗄️",
          color: "teal"
        },
        {
          title: "协作与知识管理工具",
          summary: "Notion、飞书、Confluence在AI产品团队中的协作实践，含知识库搭建和文档规范。",
          status: "可复用",
          category: "工具资源",
          audience: "AI产品经理",
          tags: ["协作", "知识管理", "工具"],
          date: "长期",
          heat: 76,
          ai: false,
          icon: "📝",
          color: "blue"
        },
        {
          title: "AI绘画与设计工具",
          summary: "Midjourney、DALL-E、Stable Diffusion、ComfyUI等AI绘图工具在产品设计中的应用场景。",
          status: "持续观察",
          category: "工具资源",
          audience: "AI产品经理",
          tags: ["AI绘画", "设计", "工具"],
          date: "长期",
          heat: 86,
          ai: true,
          icon: "🖼️",
          color: "pink"
        },
        {
          title: "低代码/无代码AI平台",
          summary: "Dify、Coze、FastGPT、Flowise等低代码AI应用搭建平台对比，含适用场景和限制分析。",
          status: "持续观察",
          category: "工具资源",
          audience: "AI产品经理",
          tags: ["低代码", "无代码", "平台"],
          date: "长期",
          heat: 90,
          ai: true,
          icon: "🧩",
          color: "purple"
        },
        /* ─── AI术语表 ─── */
        {
          title: "LLM大语言模型",
          summary: "Large Language Model 定义、架构（Transformer）、训练流程（预训练→SFT→RLHF）、能力边界详解。",
          status: "核心概念",
          category: "AI术语表",
          audience: "AI产品经理",
          tags: ["LLM", "术语", "基础"],
          date: "长期",
          heat: 95,
          ai: false,
          icon: "🧠",
          color: "blue"
        },
        {
          title: "RAG检索增强生成",
          summary: "Retrieval-Augmented Generation 原理：向量检索+上下文注入，解决幻觉和知识时效性问题。",
          status: "核心概念",
          category: "AI术语表",
          audience: "AI产品经理",
          tags: ["RAG", "术语", "检索"],
          date: "长期",
          heat: 92,
          ai: false,
          icon: "🔍",
          color: "green"
        },
        {
          title: "Agent智能体",
          summary: "AI Agent 定义：感知→规划→行动→反馈循环，工具调用、多Agent协作、自主决策能力。",
          status: "核心概念",
          category: "AI术语表",
          audience: "AI产品经理",
          tags: ["Agent", "术语", "智能体"],
          date: "长期",
          heat: 93,
          ai: true,
          icon: "🤖",
          color: "purple"
        },
        {
          title: "Fine-tuning微调",
          summary: "全参微调、LoRA、QLoRA等微调方法对比，适用场景、数据需求、成本分析。",
          status: "技术概念",
          category: "AI术语表",
          audience: "AI产品经理",
          tags: ["微调", "LoRA", "术语"],
          date: "长期",
          heat: 88,
          ai: false,
          icon: "⚙️",
          color: "orange"
        },
        {
          title: "Hallucination幻觉",
          summary: "大模型幻觉问题定义、成因分析、缓解策略：RAG、护栏、事实核查、置信度校准。",
          status: "技术概念",
          category: "AI术语表",
          audience: "AI产品经理",
          tags: ["幻觉", "术语", "风险"],
          date: "长期",
          heat: 85,
          ai: false,
          icon: "⚠️",
          color: "pink"
        },
        {
          title: "Token与上下文窗口",
          summary: "Token定义、计费方式、上下文窗口大小对产品体验的影响，长文本处理策略。",
          status: "核心概念",
          category: "AI术语表",
          audience: "AI产品经理",
          tags: ["Token", "上下文", "术语"],
          date: "长期",
          heat: 90,
          ai: false,
          icon: "🔤",
          color: "teal"
        },
        {
          title: "Embedding嵌入",
          summary: "词嵌入/句嵌入/文档嵌入原理，向量空间模型，相似度计算方法（余弦、欧氏）。",
          status: "技术概念",
          category: "AI术语表",
          audience: "AI产品经理",
          tags: ["Embedding", "向量", "术语"],
          date: "长期",
          heat: 87,
          ai: false,
          icon: "📐",
          color: "blue"
        },
        {
          title: "MCP模型上下文协议",
          summary: "Model Context Protocol 定义：标准化AI与外部工具/数据源的连接协议，生态意义和应用场景。",
          status: "前沿概念",
          category: "AI术语表",
          audience: "AI产品经理",
          tags: ["MCP", "协议", "术语"],
          date: "长期",
          heat: 91,
          ai: true,
          icon: "🔌",
          color: "purple"
        },
        /* ─── AI快速生成 ─── */
        {
          title: "AI生成PRD文档",
          summary: "输入产品名+核心场景，AI自动生成完整PRD：背景、目标、用户故事、功能需求、非功能需求、验收标准。",
          status: "可用",
          category: "AI快速生成",
          audience: "AI产品经理",
          tags: ["AI", "PRD", "生成"],
          date: "已上线",
          heat: 97,
          ai: true,
          icon: "📝",
          color: "blue"
        },
        {
          title: "AI竞品分析报告",
          summary: "输入竞品名称/URL，AI自动生成结构化竞品分析：产品定位、核心功能、交互设计、商业模式、优劣势。",
          status: "可用",
          category: "AI快速生成",
          audience: "AI产品经理",
          tags: ["AI", "竞品", "分析"],
          date: "已上线",
          heat: 95,
          ai: true,
          icon: "🔍",
          color: "green"
        },
        {
          title: "AI用户故事生成",
          summary: "输入角色+场景+目标，AI批量生成标准用户故事：As a... I want... So that... 含验收条件。",
          status: "可用",
          category: "AI快速生成",
          audience: "AI产品经理",
          tags: ["AI", "用户故事", "敏捷"],
          date: "已上线",
          heat: 93,
          ai: true,
          icon: "👤",
          color: "orange"
        },
        {
          title: "AI需求评审Checklist",
          summary: "输入产品需求描述，AI生成完整评审Checklist：功能完整性、边界条件、异常处理、性能指标、安全合规。",
          status: "可用",
          category: "AI快速生成",
          audience: "AI产品经理",
          tags: ["AI", "评审", "Checklist"],
          date: "已上线",
          heat: 91,
          ai: true,
          icon: "✅",
          color: "purple"
        },
        {
          title: "AI产品路线图生成",
          summary: "输入产品愿景+资源约束，AI生成季度产品路线图：里程碑、优先级排列、依赖关系、交付物规划。",
          status: "可用",
          category: "AI快速生成",
          audience: "AI产品经理",
          tags: ["AI", "路线图", "规划"],
          date: "已上线",
          heat: 90,
          ai: true,
          icon: "🗺️",
          color: "pink"
        }
      ]
    },
    {
      id: "content",
      num: "八",
      title: "内容创作",
      icon: "✍️",
      intro: "工作材料撰写、小红书/公众号/抖音推文编辑器、选题库、爆款复盘库、AI文案润色",
      tabs: ["工作材料", "选题库", "爆款复盘", "AI润色"],
      prompt: "请帮我撰写或润色内容：工作汇报材料、小红书/公众号/抖音文案、选题策划、爆款复盘分析。",
      tabGroups: [
        { name: "创作", tabs: ["工作材料", "选题库"] },
        { name: "优化", tabs: ["爆款复盘", "AI润色"] }
      ],
      items: [
        {
          title: "工作汇报材料模板",
          summary: "周报、月报、项目复盘、会议纪要等高频工作材料的写作模板和范例。",
          status: "可复用",
          category: "工作材料",
          audience: "职场人",
          tags: ["汇报", "模板"],
          date: "已沉淀",
          heat: 92,
          ai: true,
          icon: "📋",
          color: "blue"
        },
        {
          title: "小红书爆款选题库",
          summary: "收录各垂类高互动选题，附参考标题、封面文案和评论区运营策略。",
          status: "持续更新",
          category: "选题库",
          audience: "创作者",
          tags: ["小红书", "选题"],
          date: "本周",
          heat: 88,
          ai: true,
          icon: "📕",
          color: "pink"
        },
        {
          title: "公众号推文编辑器",
          summary: "长图文编辑器，支持 Markdown、AI 续写、排版预览和一键导出。",
          status: "可用",
          category: "工作材料",
          audience: "创作者",
          tags: ["公众号", "编辑器"],
          date: "已上线",
          heat: 85,
          ai: true,
          icon: "📝",
          color: "green"
        },
        {
          title: "爆款内容复盘库",
          summary: "拆解高传播内容的核心要素：标题结构、开头钩子、情绪曲线、互动设计。",
          status: "持续更新",
          category: "爆款复盘",
          audience: "创作者",
          tags: ["爆款", "复盘"],
          date: "本月",
          heat: 90,
          ai: true,
          icon: "🔥",
          color: "orange"
        }
      ]
    },
    {
      id: "health",
      num: "九",
      title: "健康生活中心",
      icon: "🍎",
      intro: "健康总览、饮水追踪、饮食热量(AI识别)、运动记录、睡眠管理、习惯打卡(热力图)、健康推荐(AI减脂食谱/三餐搭配/推文)",
      tabs: ["健康总览", "饮水追踪", "饮食热量", "运动记录", "睡眠管理", "习惯打卡", "健康推荐"],
      prompt: "你是健康生活助手，擅长饮水追踪、饮食营养分析、运动记录管理、睡眠质量评估、习惯打卡追踪、减脂食谱推荐、一日三餐搭配、健康推文策划。请根据用户需求给出专业、可执行的健康建议。",
      tabGroups: [
        { name: "总览", tabs: ["健康总览"] },
        { name: "饮食&饮水", tabs: ["饮水追踪", "饮食热量"] },
        { name: "运动&睡眠", tabs: ["运动记录", "睡眠管理"] },
        { name: "习惯", tabs: ["习惯打卡"] },
        { name: "推荐", tabs: ["健康推荐"] }
      ],
      items: [
        {
          title: "健康总览仪表盘",
          summary: "一屏掌握今日饮水、热量、运动、睡眠、习惯完成率，附7日趋势迷你图。",
          status: "可用",
          category: "健康总览",
          audience: "自己",
          tags: ["健康", "总览", "仪表盘"],
          date: "已上线",
          heat: 92,
          ai: false,
          icon: "📊",
          color: "blue"
        },
        {
          title: "每日饮水目标",
          summary: "建议每日饮水 2000ml，支持快速记录+目标自定义+7日趋势。",
          status: "核心原则",
          category: "饮水追踪",
          audience: "自己",
          tags: ["健康", "饮水"],
          date: "长期",
          heat: 75,
          ai: false,
          icon: "💧",
          color: "blue"
        },
        {
          title: "AI食物识别",
          summary: "拍照上传食物→AI识别→计算卡路里→营养成分分析。",
          status: "可用",
          category: "饮食热量",
          audience: "自己",
          tags: ["AI", "健康", "饮食"],
          date: "已上线",
          heat: 88,
          ai: true,
          icon: "🍽️",
          color: "orange"
        },
        {
          title: "运动记录追踪",
          summary: "记录运动类型、时长、强度，自动估算消耗热量，查看周/月统计。",
          status: "可用",
          category: "运动记录",
          audience: "自己",
          tags: ["健康", "运动", "追踪"],
          date: "已上线",
          heat: 85,
          ai: false,
          icon: "🏃",
          color: "green"
        },
        {
          title: "睡眠质量管理",
          summary: "记录入睡/起床时间、睡眠质量评分，自动计算时长与睡眠负债。",
          status: "可用",
          category: "睡眠管理",
          audience: "自己",
          tags: ["健康", "睡眠", "追踪"],
          date: "已上线",
          heat: 82,
          ai: false,
          icon: "😴",
          color: "purple"
        },
        {
          title: "习惯打卡热力图",
          summary: "自定义习惯、每日打卡、GitHub风格热力图、连续打卡streak、完成率统计。",
          status: "可用",
          category: "习惯打卡",
          audience: "自己",
          tags: ["健康", "习惯", "打卡", "热力图"],
          date: "已上线",
          heat: 90,
          ai: false,
          icon: "🔥",
          color: "orange"
        },
        {
          title: "AI减脂食谱推荐",
          summary: "输入你的体质/目标/忌口，AI生成个性化减脂食谱，含热量标注和营养配比。",
          status: "可用",
          category: "健康推荐",
          audience: "减脂人士",
          tags: ["AI", "健康", "减脂", "食谱"],
          date: "已上线",
          heat: 95,
          ai: true,
          icon: "🥗",
          color: "green"
        },
        {
          title: "一日三餐搭配",
          summary: "AI生成早餐/午餐/晚餐+加餐的完整搭配，控制总热量在1200-1600kcal区间。",
          status: "可用",
          category: "健康推荐",
          audience: "减脂人士",
          tags: ["AI", "健康", "三餐", "搭配"],
          date: "已上线",
          heat: 93,
          ai: true,
          icon: "🍱",
          color: "orange"
        },
        {
          title: "健康推文推荐",
          summary: "精选「一只白」「邪修减肥」等热门减脂推文风格，AI生成可直接发布的小红书/公众号内容。",
          status: "可用",
          category: "健康推荐",
          audience: "减脂博主",
          tags: ["AI", "健康", "推文", "小红书"],
          date: "已上线",
          heat: 91,
          ai: true,
          icon: "📝",
          color: "purple"
        }
      ]
    },
    {
      id: "materials",
      num: "十",
      title: "材料与汇报",
      icon: "📚",
      intro: "材料库、表格处理、汇报中心、模板中心、AI整理指令",
      tabs: ["材料库", "表格处理", "汇报中心", "模板中心", "AI整理指令"],
      prompt: "请把我提供的材料整理成：一句话摘要、核心事实、可引用观点、风险提示、汇报版本、后续待补充信息。",
      tabGroups: [
        { name: "材料", tabs: ["材料库", "表格处理"] },
        { name: "输出", tabs: ["汇报中心", "模板中心", "AI整理指令"] }
      ],
      items: [
        {
          title: "新能源政策材料库",
          summary: "收集政策原文、解读文章、适用项目、可引用判断。",
          status: "待整理",
          category: "材料库",
          audience: "项目/产品",
          tags: ["新能源", "政策"],
          date: "本月",
          heat: 74,
          ai: true,
          icon: "📄",
          color: "blue"
        },
        {
          title: "项目周报模板",
          summary: "固定结构：本周进展、关键问题、风险预警、下周计划、需支持事项。",
          status: "可复用",
          category: "模板中心",
          audience: "管理层",
          tags: ["周报", "模板"],
          date: "已沉淀",
          heat: 90,
          ai: true,
          icon: "📝",
          color: "green"
        }
      ]
    },
    {
      id: "review",
      num: "十一",
      title: "复盘中心",
      icon: "🌿",
      intro: "全局经验库：项目/汇报/AI/工具/内容/职业成长复盘",
      tabs: ["全部经验", "项目复盘", "汇报复盘", "AI/产品复盘", "工具研发复盘", "内容复盘", "职业成长复盘"],
      prompt: "请帮我复盘这个 case：背景、目标、做得好的地方、踩坑点、关键原因、下次可沿用的原则、需要避免的行为。",
      tabGroups: [
        { name: "总览", tabs: ["全部经验"] },
        { name: "项目与汇报", tabs: ["项目复盘", "汇报复盘"] },
        { name: "技术与内容", tabs: ["AI/产品复盘", "工具研发复盘", "内容复盘", "职业成长复盘"] }
      ],
      items: [
        {
          title: "会议后24小时内整理决议",
          summary: "会议结束后尽快把结论、责任人、截止时间和待确认事项发出。",
          status: "核心原则",
          category: "项目复盘",
          audience: "项目经理",
          tags: ["会议", "协作"],
          date: "长期沿用",
          heat: 92,
          ai: false,
          icon: "🧭",
          color: "blue"
        },
        {
          title: "AI工具分享要有真实使用场景",
          summary: "单纯罗列工具容易空泛，结合一个具体问题和前后对比更容易被理解。",
          status: "重要经验",
          category: "内容复盘",
          audience: "创作者",
          tags: ["AI工具", "内容"],
          date: "已验证",
          heat: 87,
          ai: true,
          icon: "💡",
          color: "orange"
        }
      ]
    },
    {
      id: "all",
      num: "十二",
      title: "全部入口",
      icon: "🧭",
      intro: "聚合所有中心内容、按优先级和可派AI筛选",
      tabs: ["全部", "高优先级", "可派AI", "最近更新", "模板指令"],
      prompt: "请基于我的全部工作台对象，帮我按优先级整理今天最值得推进的事项。",
      tabGroups: [],
      items: []
    }
  ],
  statuses: ["全部", "待办", "进行中", "已完成", "可用", "待整理", "待复盘", "持续维护", "核心原则", "草稿", "待修改", "可发布", "已发布", "在读", "想读", "已读", "待读"],
  audiences: ["全部", "项目经理", "AI产品经理", "创作者", "管理层", "自己", "项目/产品", "业务/研发"],
  colors: {
    blue: { color: "#5277ff", soft: "#eaf0ff" },
    green: { color: "#52c41a", soft: "#e8f8e0" },
    purple: { color: "#8b6cff", soft: "#f1edff" },
    orange: { color: "#f5a524", soft: "#fff4db" },
    pink: { color: "#f071a8", soft: "#fff0f6" }
  }
};
